### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by samselikoff** [broccolijs/broccoli-multifilter#1]
Excited about this, is the idea to deprecate broccoli-filter (since 1-1 is a particular case of m-n)? Or is broccoli-filter still going to play an important role in the Broccoli ecosystem?

If the idea is to deprecate, could we 🚲 🏠  on the name?

**Comment by rwjblue** [comment]
I don't think we would deprecate, at least not in the near term.

**Comment by joliss** [comment]
What @rwjblue said. The API is a bit different, and it doesn't handle pass-through well at the moment.
